pipeline {
    agent any

    environment {
        NODE_ENV = 'production'
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://git.toptal.com/henrique/node-3tier-app2.git', branch: 'master'
            }
        }
        stage('Install Dependencies') {
            steps {
                script {
                    dir('api') {
                        sh 'npm install'
                    }
                    dir('web') {
                        sh 'npm install'
                    }
                }
            }
        }
        stage('Build') {
            steps {
                script {
                    dir('api') {
                        sh 'npm run build'
                    }
                    dir('web') {
                        sh 'npm run build'
                    }
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    dir('api') {
                        sh 'npm test'
                    }
                    dir('web') {
                        sh 'npm test'
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    dir('scripts') {
                        sh './deploy.sh'
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
